name = "kebab-rating-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
FRONTEND_URL = "https://kebab-rating.pages.dev"
[[services]]
binding = "AUTH_SERVICE"
service = "auth"

[[d1_databases]]
binding = "DB"
database_name = "kebab-rating-db"
database_id = "caef9281-8598-49ea-9a63-32b8f3efb857"
