name = "kebab-rating-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
FRONTEND_URL = "https://kebab-rating.pages.dev"
# Odkaz na tvůj nasazený auth worker service
AUTH_SERVICE_URL = "https://auth.v-vizvary.workers.dev"
